DEFINE input:inference "schema-inference-rules"


# get pmid MeSH annotations


select distinct (strafter(str(?pmid), "http://rdf.ncbi.nlm.nih.gov/pubchem/reference/PMID") as ?PMID) (strafter(STR(?mesh),"http://id.nlm.nih.gov/mesh/") as ?MESH)
where
{
    {
        select ?pmid
        where
        {
            ?pmid a fabio:Article .
        }
        ORDER BY RAND()
        LIMIT 1000
    }
?pmid a fabio:Article .
?pmid (fabio:hasSubjectTerm|fabio:hasSubjectTerm/meshv:hasDescriptor) ?mesh .
?mesh a meshv:TopicalDescriptor .
?mesh meshv:active 1 .
?mesh meshv:treeNumber ?tn .
FILTER(REGEX(?tn,"(C|A|G|F|I|J|D20|D23|D26|D27)")) .
}



# get MeSH ancestors (OBSOLETE)

select distinct (strafter(STR(?mesh),"http://id.nlm.nih.gov/mesh/") as ?MESH) (strafter(STR(?ancestor),"http://id.nlm.nih.gov/mesh/") as ?MESH_ANCESTOR)
where
{
    
    ?mesh meshv:treeNumber ?tn .
    FILTER(REGEX(?tn,"(C|A|G|F|I|J|D20|D23|D26|D27)")) .
    ?tn meshv:parentTreeNumber ?tn_ancestor .
    ?ancestor meshv:treeNumber ?tn_ancestor .

}

OR 

select distinct (strafter(STR(?mesh),"http://id.nlm.nih.gov/mesh/") as ?MESH) (strafter(STR(?ancestor),"http://id.nlm.nih.gov/mesh/") as ?MESH_ANCESTOR)
where
{
    ?mesh a meshv:TopicalDescriptor .
    ?mesh meshv:active 1 .
    ?mesh (meshv:treeNumber|meshv:treeNumber/meshv:parentTreeNumber) ?tn .
    FILTER(REGEX(?tn,"(C|A|G|F|I|J|D20|D23|D26|D27)")) .
    ?ancestor meshv:treeNumber ?tn .
    ?ancestor a meshv:TopicalDescriptor .
    ?ancestor meshv:active 1 .
}

# get mesh

select distinct (strafter(STR(?mesh),"http://id.nlm.nih.gov/mesh/") as ?MESH)
where
{
    ?mesh a meshv:TopicalDescriptor .
    ?mesh meshv:active 1 .
    ?mesh meshv:treeNumber ?tn .
    FILTER(REGEX(?tn,"(C|A|G|F|I|J|D20|D23|D26|D27)")) .

}